### ISSUE TITLE
Consistent framing of input fields

### ISSUE THREAD

**Issue by vogti** [polypheny-db/Polypheny-DB#44]
Some of the input fields a framed green (for valid inputs?) while others are not. This should be consistent. Or is there a specific reason why this is handled like this?

**Comment by nilshansen94** [comment]
The green input fields appear only for numeric inputs. In the first attempt, an input of type number was used to avoid invalid input to some extent, but this caused problem with the angular data binding. Now, also for numeric data-types an input of type text is used and the green/red classes show, if the value is of a numeric type. It makes no sense to validate varchar/text input, since any input is allowed there.
But it can make someone wonder, I agree. A possibility would be to do no validation in the UI and simply throw an error, if the row could not be inserted.

**Comment by vogti** [comment]
There is at least one thing you can check for VARCHARs: the length. For Text fields I agree that it is difficult to find something to validate. But in that case I would suggest that you always frame it green (because it is always a valid string). I think the validation is quite useful and we should not drop it because there are fields without something to validate.

**Comment by vogti** [comment]
Still missing for 

- Add index
- Add schema

**Comment by nilshansen94** [comment]
When filling in the name of a schema that you want to drop, the validation checks if the schema in the input field exists at all. If yes, the input field will be marked valid.

**Comment by vogti** [comment]
It would make sense to do a similar check for the create schema form. 
![grafik](https://user-images.githubusercontent.com/1682115/68528456-24724b00-02f3-11ea-87a4-3049ea07be37.png)

**Comment by vogti** [comment]
The "if not exists" and the "if exists" checkboxes do no longer make sense due to the validation. Consider removing these checkboxes.

**Comment by vogti** [comment]
It would make sense to also add such a check for create table.
![grafik](https://user-images.githubusercontent.com/1682115/68528566-c47ca400-02f4-11ea-9437-2d8f3fe163bb.png)
